In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Data Cleaning & Preparation

## DecodeLabs Tasks

Project 1

Author: Vicky Sharma

In [ ]:
df = pd.read_csv("raw_dataset.csv")
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
df.shape

(1200, 14)

In [15]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='str')

In [16]:
df.info

<bound method DataFrame.info of         OrderID        Date CustomerID  Product  Quantity  UnitPrice  \
0     ORD200000  2023-01-04     C72649  Monitor         5     570.62
1     ORD200001  2024-08-23     C75739    Phone         2     151.35
2     ORD200002  2024-02-27     C81728   Tablet         5     550.68
3     ORD200003  2023-10-15     C33540    Chair         1     273.19
4     ORD200004  2025-05-08     C81840  Printer         4     626.01
...         ...         ...        ...      ...       ...        ...
1195  ORD201195  2024-06-20     C21126     Desk         1     107.04
1196  ORD201196  2024-03-04     C20095  Monitor         2     662.53
1197  ORD201197  2023-07-13     C79674   Tablet         2     436.84
1198  ORD201198  2024-08-22     C64753    Chair         4     262.52
1199  ORD201199  2023-06-11     C57502   Tablet         4     560.58

     ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0        928 Main St    Debit Card     Shipped    TRK37947903            7
1        823 Main St        Online     Shipped    TRK91186779            3
2        512 Main St   Credit Card   Cancelled    TRK42903982            8
3        275 Main St    Debit Card    Returned    TRK62788070            5
4        668 Main St        Online   Delivered    TRK29241424            8
...              ...           ...         ...            ...          ...
1195     392 Main St   Credit Card   Cancelled    TRK38009181            6
1196     778 Main St        Online   Cancelled    TRK69207593            5
1197     275 Main St        Online   Delivered    TRK88039356            2
1198     509 Main St    Debit Card   Cancelled    TRK71683331            4
1199     201 Main St     Gift Card    Returned    TRK51116746            6

     CouponCode ReferralSource  TotalPrice
0        SAVE10      Instagram     2853.10
1        SAVE10       Referral      302.70
2      FREESHIP          Email     2753.40
3        SAVE10       Facebook      273.19
4        SAVE10          Email     2504.04
...         ...            ...         ...
1195   FREESHIP         Google      107.04
1196        NaN       Facebook     1325.06
1197   FREESHIP      Instagram      873.68
1198   WINTER15      Instagram     1050.08
1199     SAVE10       Referral     2242.32

[1200 rows x 14 columns]>

In [17]:
df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [18]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.dtypes

OrderID                str
Date                   str
CustomerID             str
Product                str
Quantity             int64
UnitPrice          float64
ShippingAddress        str
PaymentMethod          str
OrderStatus            str
TrackingNumber         str
ItemsInCart          int64
CouponCode             str
ReferralSource         str
TotalPrice         float64
dtype: object

In [22]:
df["Date"] = pd.to_datetime(df["Date"])

In [23]:
df.dtypes

OrderID                       str
Date               datetime64[us]
CustomerID                    str
Product                       str
Quantity                    int64
UnitPrice                 float64
ShippingAddress               str
PaymentMethod                 str
OrderStatus                   str
TrackingNumber                str
ItemsInCart                 int64
CouponCode                    str
ReferralSource                str
TotalPrice                float64
dtype: object

In [24]:
df["Date"].head()

0   2023-01-04
1   2024-08-23
2   2024-02-27
3   2023-10-15
4   2025-05-08
Name: Date, dtype: datetime64[us]

In [25]:
df["OrderStatus"].unique()

<StringArray>
['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending']
Length: 5, dtype: str

In [26]:
df["PaymentMethod"].unique()

<StringArray>
['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash']
Length: 5, dtype: str

In [27]:
df["CouponCode"].unique()

<StringArray>
['SAVE10', 'FREESHIP', nan, 'WINTER15']
Length: 4, dtype: str

In [28]:
df["CouponCode"].value_counts(dropna=False)

CouponCode
FREESHIP    313
NaN         309
WINTER15    292
SAVE10      286
Name: count, dtype: int64

In [29]:
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [30]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [31]:
df = df.drop_duplicates()

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df["CalculatedPrice"] = df["Quantity"] * df["UnitPrice"]

In [34]:
df[["Quantity", "UnitPrice", "TotalPrice", "CalculatedPrice"]].head()

   Quantity  UnitPrice  TotalPrice  CalculatedPrice
0         5     570.62     2853.10          2853.10
1         2     151.35      302.70           302.70
2         5     550.68     2753.40          2753.40
3         1     273.19      273.19           273.19
4         4     626.01     2504.04          2504.04

In [36]:
df.to_csv("cleaned_dataset.csv", index=False)

In [38]:
cleaned_df = pd.read_csv("cleaned_dataset.csv")
cleaned_df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,CalculatedPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,2504.04